services:
  - type: web
    name: sentiment-analysis-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python nltk_setup.py && python train_models.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0